version: '3.8'

services:
  # Serveur OBD SaaS
  obd-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: obd-saas-server
    restart: unless-stopped
    
    # Ports
    ports:
      - "3000:3000"   # Interface web et API
      - "6909:6909"   # TCP pour boîtiers OBD
    
    # Variables d'environnement
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TCP_PORT=6909
      - LOG_LEVEL=info
      # Supabase (à configurer dans Coolify)
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}
      # Sécurité
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - SOCKET_CORS_ORIGIN=${SOCKET_CORS_ORIGIN:-*}
      # Rate limiting
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
    
    # Volumes pour persistance des logs
    volumes:
      - obd_logs:/app/logs
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  obd_logs:
    driver: local

networks:
  default:
    name: coolify 